### ISSUE TITLE
It does not handle small differences of platform version

### ISSUE THREAD

**Issue by ikuwow** [chef-cookbooks/httpd#25]
Ubuntu 14.10 is seems to be unsupported, because `templates/default/2.4/sysvinit/ubuntu-14.10/apache2.erb` does not exist.

The error message is appeared by test-kitchen: (sorry for very long message)

```
         * httpd_service[default] action start
           * template[default :create /etc/init.d/apache2-default] action create

             ================================================================================
             Error executing action `create` on resource 'template[default :create /etc/init.d/apache2-default]'
             ================================================================================

             Chef::Exceptions::FileNotFound
             ------------------------------
             Cookbook 'httpd' (0.2.6) does not contain a file at any of these locations:
        templates/ubuntu-14.10/2.4/sysvinit/ubuntu-14.10/apache2.erb
        templates/ubuntu/2.4/sysvinit/ubuntu-14.10/apache2.erb
        templates/default/2.4/sysvinit/ubuntu-14.10/apache2.erb
        templates/2.4/sysvinit/ubuntu-14.10/apache2.erb

             This cookbook _does_ contain: ['/tmp/kitchen/cache/cookbooks/httpd/templates/default/module_load.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/rhel/sysconfig/httpd-2.4.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/httpd.conf.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/envvars.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/2.4/mods/rhel/mpm.conf.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/rhel/sysconfig/httpd-2.2.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/magic.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/2.4/scripts/a2enmod.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/2.4/sysvinit/ubuntu-14.04/apache2.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/2.2/sysvinit/el-5/httpd.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/mpm.conf.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/systemd/httpd.service.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/2.4/sysvinit/el-6/httpd.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/2.2/mods/mpm.conf.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/2.2/scripts/a2enmod.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/2.2/sysvinit/debian-7/apache2.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/2.2/sysvinit/el-6/httpd.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/2.2/sysvinit/ubuntu-12.04/apache2.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/2.2/sysvinit/ubuntu-10.04/apache2.erb']

             Resource Declaration:
             ---------------------
       # In /tmp/kitchen/cache/cookbooks/httpd/libraries/provider_httpd_service_debian_sysvinit.rb

       20:             template "#{new_resource.name} :create /etc/init.d/#{apache_name}" do
       21:               path "/etc/init.d/#{apache_name}"
       22:               source "#{apache_version}/sysvinit/#{platform_and_version}/apache2.erb"
       23:               owner 'root'
       24:               group 'root'
       25:               mode '0755'
       26:               variables(apache_name: apache_name)
       27:               cookbook 'httpd'
       28:               action :create
       29:             end
       30:

             Compiled Resource:
             ------------------
             # Declared in /tmp/kitchen/cache/cookbooks/httpd/libraries/provider_httpd_service_debian_sysvinit.rb:20:in `block in <class:Sysvinit>'

             template("default :create /etc/init.d/apache2-default") do
        action [:create]
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        path "/etc/init.d/apache2-default"
        backup 5
        atomic_update true

        cookbook "httpd"
        variables {:apache_name=>"apache2-default"}
        declared_type :template
        cookbook_name "webapps"
        owner "root"
        group "root"
        mode "0755"
             end


           ================================================================================
           Error executing action `start` on resource 'httpd_service[default]'
           ================================================================================

           Chef::Exceptions::FileNotFound
           ------------------------------
           template[default :create /etc/init.d/apache2-default] (/tmp/kitchen/cache/cookbooks/httpd/libraries/provider_httpd_service_debian_sysvinit.rb line 20) had an error: Chef::Exceptions::FileNotFound: Cookbook 'httpd' (0.2.6) does not contain a file at any of these locations:
             templates/ubuntu-14.10/2.4/sysvinit/ubuntu-14.10/apache2.erb
             templates/ubuntu/2.4/sysvinit/ubuntu-14.10/apache2.erb
             templates/default/2.4/sysvinit/ubuntu-14.10/apache2.erb
             templates/2.4/sysvinit/ubuntu-14.10/apache2.erb

           This cookbook _does_ contain: ['/tmp/kitchen/cache/cookbooks/httpd/templates/default/module_load.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/rhel/sysconfig/httpd-2.4.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/httpd.conf.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/envvars.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/2.4/mods/rhel/mpm.conf.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/rhel/sysconfig/httpd-2.2.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/magic.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/2.4/scripts/a2enmod.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/2.4/sysvinit/ubuntu-14.04/apache2.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/2.2/sysvinit/el-5/httpd.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/mpm.conf.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/systemd/httpd.service.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/2.4/sysvinit/el-6/httpd.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/2.2/mods/mpm.conf.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/2.2/scripts/a2enmod.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/2.2/sysvinit/debian-7/apache2.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/2.2/sysvinit/el-6/httpd.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/2.2/sysvinit/ubuntu-12.04/apache2.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/2.2/sysvinit/ubuntu-10.04/apache2.erb']

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/webapps/recipes/default.rb

        10: httpd_service 'default' do
            11:     action [:create, :start]
            12: end

           Compiled Resource:
           ------------------
       # Declared in /tmp/kitchen/cache/cookbooks/webapps/recipes/default.rb:10:in `from_file'

           httpd_service("default") do
             action [:create, :start]
             updated true
             retries 0

             default_guard_interpreter :default
             declared_type :httpd_service
             cookbook_name "webapps"
             recipe_name "default"
             instance "default"
             timeout "400"
             log_level "warn"
             keepalive true
             maxkeepaliverequests "100"
             keepalivetimeout "5"
             hostname_lookups "off"
             listen_addresses ["0.0.0.0"]

           end


         templates/ubuntu-14.10/2.4/sysvinit/ubuntu-14.10/apache2.erb
         templates/ubuntu/2.4/sysvinit/ubuntu-14.10/apache2.erb
         templates/default/2.4/sysvinit/ubuntu-14.10/apache2.erb
         templates/2.4/sysvinit/ubuntu-14.10/apache2.erb

       This cookbook _does_ contain: ['/tmp/kitchen/cache/cookbooks/httpd/templates/default/module_load.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/rhel/sysconfig/httpd-2.4.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/httpd.conf.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/envvars.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/2.4/mods/rhel/mpm.conf.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/rhel/sysconfig/httpd-2.2.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/magic.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/2.4/scripts/a2enmod.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/2.4/sysvinit/ubuntu-14.04/apache2.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/2.2/sysvinit/el-5/httpd.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/mpm.conf.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/systemd/httpd.service.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/2.4/sysvinit/el-6/httpd.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/2.2/mods/mpm.conf.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/2.2/scripts/a2enmod.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/2.2/sysvinit/debian-7/apache2.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/2.2/sysvinit/el-6/httpd.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/2.2/sysvinit/ubuntu-12.04/apache2.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/2.2/sysvinit/ubuntu-10.04/apache2.erb']

       Running handlers:
       [2015-03-16T02:35:37+00:00] ERROR: Running exception handlers
       Running handlers complete

       [2015-03-16T02:35:37+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       Chef Client failed. 81 resources updated in 42.035333268 seconds
       [2015-03-16T02:35:37+00:00] ERROR: Found 1 errors, they are stored in the backtrace
       [2015-03-16T02:35:38+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
>>>>>> Converge failed on instance <default-ubuntu-1410>.
>>>>>> Please see .kitchen/logs/default-ubuntu-1410.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: SSH exited (1) for command: [sh -c '
sudo -E /opt/chef/bin/chef-client --local-mode --config /tmp/kitchen/client.rb --log_level auto --force-formatter --no-color --chef-zero-port 8889 --json-attributes /tmp/kitchen/dna.json
']
>>>>>> ----------------------
```

I can imagine it properly works after copying templates/default/2.4/sysvinit/ubuntu-14.04/apache2.erb to templates/default/2.4/sysvinit/ubuntu-14.10/apache2.erb.
Is there any major changes in init script in Ubuntu 14.10?
Is this cookbook is only for ubuntu 14.04?

I think the main problem is this cookbook does not handle small differences of platform version like this.

**Comment by tas50** [comment]
Closing this one out now since 14.10 is EOL
