### ISSUE TITLE
Resource creation fails on log_config module when using AWS Linux

### ISSUE THREAD

**Issue by rgriffith** [chef-cookbooks/httpd#45]
I have a client node on AWS running on AWS Linux (RHEL) that is showing the following error during `httpd_service` creation. This error does not occur when testing locally with test kitchen on a CentOS VM.
### Stack Trace from AWS node

```
Recipe: cascade::apache2
  * httpd_service[cascade-apache2] action create
    * yum_package[cascade-apache2 :create httpd] action install (up to date)
    * service[cascade-apache2 :create httpd] action stop (up to date)
    * service[cascade-apache2 :create httpd] action disable (up to date)
    * yum_package[cascade-apache2 :create net-tools] action install (up to date)
    * httpd_module[cascade-apache2 :create log_config] action create
      * yum_package[cascade-apache2 :create log_config :create ] action install
        * No candidate version available for cascade-apache2 :create log_config :create 
        ================================================================================
        Error executing action `install` on resource 'yum_package[cascade-apache2 :create log_config :create ]'
        ================================================================================

        Chef::Exceptions::Package
        -------------------------
        No candidate version available for cascade-apache2 :create log_config :create 

        Resource Declaration:
        ---------------------
        # In /var/chef/cache/cookbooks/httpd/libraries/provider_httpd_module_rhel.rb

         21:         package "#{new_resource.name} :create #{parsed_module_package_name}" do
         22:           package_name parsed_module_package_name
         23:           action :install
         24:         end
         25: 

        Compiled Resource:
        ------------------
        # Declared in /var/chef/cache/cookbooks/httpd/libraries/provider_httpd_module_rhel.rb:21:in `block in <class:HttpdModuleRhel>'

        yum_package("cascade-apache2 :create log_config :create ") do
          action [:install]
          retries 0
          retry_delay 2
          default_guard_interpreter :default
          package_name "cascade-apache2 :create log_config :create "
          flush_cache {:before=>false, :after=>false}
          declared_type :package
          cookbook_name "cascade"
        end


      ================================================================================
      Error executing action `create` on resource 'httpd_module[cascade-apache2 :create log_config]'
      ================================================================================

      Chef::Exceptions::Package
      -------------------------
      yum_package[cascade-apache2 :create log_config :create ] (/var/chef/cache/cookbooks/httpd/libraries/provider_httpd_module_rhel.rb line 21) had an error: Chef::Exceptions::Package: No candidate version available for cascade-apache2 :create log_config :create 

      Resource Declaration:
      ---------------------
      # In /var/chef/cache/cookbooks/httpd/libraries/provider_httpd_service_rhel.rb

       45:             httpd_module "#{new_resource.name} :create #{m}" do
       46:               module_name m
       47:               httpd_version parsed_version
       48:               instance new_resource.instance
       49:               action :create
       50:             end
       51:           end

      Compiled Resource:
      ------------------
      # Declared in /var/chef/cache/cookbooks/httpd/libraries/provider_httpd_service_rhel.rb:45:in `block (2 levels) in <class:HttpdServiceRhel>'

      httpd_module("cascade-apache2 :create log_config") do
        action [:create]
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        declared_type :httpd_module
        cookbook_name "cascade"
        instance "cascade-apache2"
        module_name "log_config"
      end


    ================================================================================
    Error executing action `create` on resource 'httpd_service[cascade-apache2]'
    ================================================================================

    Chef::Exceptions::Package
    -------------------------
    httpd_module[cascade-apache2 :create log_config] (/var/chef/cache/cookbooks/httpd/libraries/provider_httpd_service_rhel.rb line 45) had an error: Chef::Exceptions::Package: yum_package[cascade-apache2 :create log_config :create ] (/var/chef/cache/cookbooks/httpd/libraries/provider_httpd_module_rhel.rb line 21) had an error: Chef::Exceptions::Package: No candidate version available for cascade-apache2 :create log_config :create 

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/cascade/recipes/apache2.rb

     42: httpd_service 'cascade-apache2' do
     43:   modules ['rewrite', 'ssl', 'proxy', 'proxy_ajp']
     44:   package_name 'httpd'
     45:   action [:create, :start]
     46: end
     47: 

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/cascade/recipes/apache2.rb:42:in `from_file'

    httpd_service("cascade-apache2") do
      action [:create, :start]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :httpd_service
      cookbook_name "cascade"
      recipe_name "apache2"
      modules ["rewrite", "ssl", "proxy", "proxy_ajp"]
      package_name "httpd"
      instance "cascade-apache2"
    end


Running handlers:
[2015-08-06T13:06:22-05:00] ERROR: Running exception handlers
Running handlers complete
[2015-08-06T13:06:22-05:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 13.709229297 seconds
[2015-08-06T13:06:22-05:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2015-08-06T13:06:22-05:00] ERROR: httpd_service[cascade-apache2] (cascade::apache2 line 42) had an error: Chef::Exceptions::Package: httpd_module[cascade-apache2 :create log_config] (/var/chef/cache/cookbooks/httpd/libraries/provider_httpd_service_rhel.rb line 45) had an error: Chef::Exceptions::Package: yum_package[cascade-apache2 :create log_config :create ] (/var/chef/cache/cookbooks/httpd/libraries/provider_httpd_module_rhel.rb line 21) had an error: Chef::Exceptions::Package: No candidate version available for cascade-apache2 :create log_config :create 
[2015-08-06T13:06:23-05:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```
### Stack Trace from Test Kitchen

```
Recipe: cascade::apache2
    * yum_package[cascade-apache2 :create httpd] action install (up to date)
 (up to date)
 (up to date)
 (up to date)

 (up to date)
 (up to date)
      * template[cascade-apache2 :create log_config :create /etc/httpd-cascade-apache2/conf.d/log_config.load] action create (up to date)
(up to date)

 (up to date)
 (up to date)
 (up to date)
(up to date)
 (up to date)
    * link[cascade-apache2 :create /usr/sbin/httpd-cascade-apache2.worker] action create (up to date)
    * link[cascade-apache2 :create /usr/sbin/httpd-cascade-apache2.event] action create (up to date)

      * directory[cascade-apache2 :create mpm_worker :create /etc/httpd-cascade-apache2/conf.d] action create (up to date)
 (up to date)
(up to date)
 (up to date)
 (up to date)
 (up to date)
 (up to date)
    * directory[cascade-apache2 :create /var/log/httpd-cascade-apache2] action create (up to date)
    * link[cascade-apache2 :create /etc/httpd-cascade-apache2/logs] action create (up to date)
    * link[cascade-apache2 :create /etc/httpd-cascade-apache2/modules] action create (up to date)
    * directory[cascade-apache2 :create /var/run/httpd-cascade-apache2] action create (up to date)
    * link[cascade-apache2 :create /etc/httpd-cascade-apache2/run] action create (up to date)
 (up to date)
 (up to date)

      * yum_package[cascade-apache2 :create rewrite :create httpd] action install (up to date)
 (up to date)
 (up to date)
(up to date)

 (up to date)
      * directory[cascade-apache2 :create ssl :create /etc/httpd-cascade-apache2/conf.d] action create (up to date)
 (up to date)
(up to date)

      * yum_package[cascade-apache2 :create proxy :create httpd] action install (up to date)
 (up to date)
 (up to date)
(up to date)

      * yum_package[cascade-apache2 :create proxy_ajp :create httpd] action install (up to date)
      * directory[cascade-apache2 :create proxy_ajp :create /etc/httpd-cascade-apache2/conf.d] action create (up to date)
 (up to date)
(up to date)
     (up to date)

 (up to date)
 (up to date)
 (up to date)
 (up to date)
     (up to date)

 (up to date)
 (up to date)
     (up to date)

Running handlers:
Running handlers complete
Chef Client finished, 0/78 resources updated in 9.334210483 seconds
Finished converging <default-centos-65> (0m12.81s).
-----> Kitchen is finished. (0m13.72s)
```

**Comment by cheeseplus** [comment]
It appears that there is something wrong with the code itself if you could snippet or post that we could further troubleshoot.

**Comment by rgriffith** [comment]
I am no longer running into this issue, but do want to take this time to mention I am running into another issue with the latest Amazon Linux AMI. I reported this on #103 because the stack trace I was seeing is similar
