### ISSUE TITLE
Cannot create/start httpd_service on 2015.03 Amazon AMI Linux Node

### ISSUE THREAD

**Issue by michaelgreenwell** [chef-cookbooks/httpd#46]
I am trying to install onto an Amazon EC2 node running the 2015.03 version of the Amazon Linux AMI. I'm running into an issue where my webserver recipe fails because it cannot create the http_service[customers] resource:

```
================================================================================
Error executing action `create` on resource 'httpd_service[customers]'
================================================================================

NoMethodError
-------------
undefined method `each' for nil:NilClass 

Cookbook Trace:
---------------
/var/chef/cache/cookbooks/httpd/libraries/provider_httpd_service_rhel.rb:247:in `block in <class:HttpdServiceRhel>'

Resource Declaration: 
---------------------

# In /var/chef/cache/cookbooks/awesome_customers/recipes/webserver.rb
  2: httpd_service 'customers' do
  3:   mpm 'prefork'
  4:   action [:create, :start]
  5: end
6: 

Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/awesome_customers/recipes/webserver.rb:2:in `from_file'

httpd_service("customers") do
  action [:create, :start]
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  declared_type :httpd_service
  cookbook_name "awesome_customers"
  recipe_name "webserver"
  mpm "prefork"
  instance "customers"
end
```

I can manually set the version to either 2.2 or 2.4 in the webserver.rb file, but then it appears to have an issue with my node's platform_version attribute, which doesn't appear to have a default configuration in this community cookbook:

```
================================================================================
Error executing action `start` on resource 'httpd_service[customers]'
================================================================================

Chef::Exceptions::FileNotFound
------------------------------
template[customers :create /etc/init.d/httpd-customers] (/var/chef/cache/cookbooks/httpd/libraries/provider_httpd_service_rhel_sysvinit.rb line 14) had an error: Chef::Exceptions::FileNotFound: Cookbook 'httpd' (0.2.18) does not contain a file at any of these locations:
  templates/amazon-2015.03/2.4/sysvinit/el-2015/httpd.erb
  templates/amazon/2.4/sysvinit/el-2015/httpd.erb
  templates/default/2.4/sysvinit/el-2015/httpd.erb
  templates/2.4/sysvinit/el-2015/httpd.erb

This cookbook _does_ contain: ['/var/chef/cache/cookbooks/httpd/templates/default/2.2/mods/mpm.conf.erb','/var/chef/cache/cookbooks/httpd/templates/default/2.2/scripts/a2enmod.erb','/var/chef/cache/cookbooks/httpd/templates/default/2.2/sysvinit/debian-7/apache2.erb','/var/chef/cache/cookbooks/httpd/templates/default/2.2/sysvinit/el-6/httpd.erb','/var/chef/cache/cookbooks/httpd/templates/default/2.2/sysvinit/ubuntu-10.04/apache2.erb','/var/chef/cache/cookbooks/httpd/templates/default/2.2/sysvinit/ubuntu-12.04/apache2.erb','/var/chef/cache/cookbooks/httpd/templates/default/2.4/mods/rhel/mpm.conf.erb','/var/chef/cache/cookbooks/httpd/templates/default/2.4/scripts/a2enmod.erb','/var/chef/cache/cookbooks/httpd/templates/default/2.4/sysvinit/el-6/httpd.erb','/var/chef/cache/cookbooks/httpd/templates/default/2.4/sysvinit/ubuntu-14.04/apache2.erb','/var/chef/cache/cookbooks/httpd/templates/default/envvars.erb','/var/chef/cache/cookbooks/httpd/templates/default/httpd.conf.erb','/var/chef/cache/cookbooks/httpd/templates/default/module_load.erb','/var/chef/cache/cookbooks/httpd/templates/default/mpm.conf.erb','/var/chef/cache/cookbooks/httpd/templates/default/rhel/sysconfig/httpd-2.2.erb','/var/chef/cache/cookbooks/httpd/templates/default/rhel/sysconfig/httpd-2.4.erb','/var/chef/cache/cookbooks/httpd/templates/default/systemd/httpd.service.erb','/var/chef/cache/cookbooks/httpd/templates/default/magic.erb','/var/chef/cache/cookbooks/httpd/templates/default/2.2/sysvinit/el-5/httpd.erb']

Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/awesome_customers/recipes/webserver.rb

  2: httpd_service 'customers' do
  3:   version '2.4'
  4:   mpm 'prefork'
  5:   action [:create, :start]
  6: end
  7: 

Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/awesome_customers/recipes/webserver.rb:2:in `from_file'

httpd_service("customers") do
  action [:create, :start]
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  declared_type :httpd_service
  cookbook_name "awesome_customers"
  recipe_name "webserver"
  version "2.4"
  mpm "prefork"
  instance "customers"
  timeout "400"
  log_level "warn"
  keepalive true
  maxkeepaliverequests "100"
  keepalivetimeout "5"
  hostname_lookups "off"
  listen_addresses ["0.0.0.0"]
  listen_ports ["80"]
end
```

I'm running chef-client 12.4.1 on both my workstation and the node:

Workstation:
```
Chef Development Kit Version: 0.7.0
chef-client version: 12.4.1
berks version: 3.2.4
kitchen version: 1.4.2
```

Node:
```
chef-client --version
Chef: 12.4.1
```

Does anyone have any suggestions for how i might resolve this issue?

**Comment by tpetchel** [comment]
I queued a potential fix here: https://github.com/chef-cookbooks/httpd/pull/47.

**Comment by Micka33** [comment]
Looks like I have the same issue
```console
192-168-10-98
192-168-10-98 Starting Chef Client, version 12.5.1
192-168-10-98 resolving cookbooks for run list: ["awesome_customers"]
192-168-10-98 Synchronizing Cookbooks:
192-168-10-98   - apt (2.8.2)
192-168-10-98   - httpd (0.3.0)
192-168-10-98   - compat_resource (12.5.9)
192-168-10-98   - awesome_customers (0.1.1)
192-168-10-98 Compiling Cookbooks...
192-168-10-98 Converging 16 resources
192-168-10-98 Recipe: apt::default
192-168-10-98   * file[/var/lib/apt/periodic/update-success-stamp] action nothing (skipped due to action :nothing)
192-168-10-98   * directory[/etc/apt/apt.conf.d] action create (up to date)
192-168-10-98   * cookbook_file[/etc/apt/apt.conf.d/15update-stamp] action create (up to date)
192-168-10-98   * execute[apt-get-update] action run (skipped due to not_if)
192-168-10-98   * execute[apt-get update] action nothing (skipped due to action :nothing)
192-168-10-98   * execute[apt-get autoremove] action nothing (skipped due to action :nothing)
192-168-10-98   * execute[apt-get autoclean] action nothing (skipped due to action :nothing)
192-168-10-98   * execute[apt-get-update-periodic] action run (skipped due to only_if)
192-168-10-98   * directory[/var/cache/local] action create (up to date)
192-168-10-98   * directory[/var/cache/local/preseeding] action create (up to date)
192-168-10-98 Recipe: awesome_customers::user
192-168-10-98   * group[web_admin] action create (up to date)
192-168-10-98   * user[web_admin] action create (up to date)
192-168-10-98 Recipe: awesome_customers::webserver
192-168-10-98   * httpd_service_debian_sysvinit[customers] action create
192-168-10-98
192-168-10-98     ================================================================================
192-168-10-98     Error executing action `create` on resource 'httpd_service_debian_sysvinit[customers]'
192-168-10-98     ================================================================================
192-168-10-98
192-168-10-98     NoMethodError
192-168-10-98     -------------
192-168-10-98     undefined method `each' for nil:NilClass
192-168-10-98
192-168-10-98     Cookbook Trace:
192-168-10-98     ---------------
192-168-10-98     /var/chef/cache/cookbooks/httpd/libraries/httpd_service_debian.rb:289:in `block in <class:HttpdServiceDebian>'
192-168-10-98
192-168-10-98     Resource Declaration:
192-168-10-98     ---------------------
192-168-10-98     # In /var/chef/cache/cookbooks/awesome_customers/recipes/webserver.rb
192-168-10-98
192-168-10-98       7: httpd_service 'customers' do
192-168-10-98       8:   mpm 'prefork'
192-168-10-98       9:   action [:create, :start]
192-168-10-98      10: end
192-168-10-98      11:
192-168-10-98
192-168-10-98     Compiled Resource:
192-168-10-98     ------------------
192-168-10-98     # Declared in /var/chef/cache/cookbooks/awesome_customers/recipes/webserver.rb:7:in `from_file'
192-168-10-98
192-168-10-98     httpd_service_debian_sysvinit("customers") do
192-168-10-98       action [:create, :start]
192-168-10-98       retries 0
192-168-10-98       retry_delay 2
192-168-10-98       default_guard_interpreter :default
192-168-10-98       declared_type :httpd_service
192-168-10-98       cookbook_name "awesome_customers"
192-168-10-98       recipe_name "webserver"
192-168-10-98       mpm "prefork"
192-168-10-98       instance "customers"
192-168-10-98       run_user "www-data"
192-168-10-98       run_group "www-data"
192-168-10-98       servername "192-168-10-98"
192-168-10-98     end
192-168-10-98
192-168-10-98
192-168-10-98 Running handlers:
192-168-10-98 [2015-10-12T16:34:35+00:00] ERROR: Running exception handlers
192-168-10-98 Running handlers complete
192-168-10-98 [2015-10-12T16:34:35+00:00] ERROR: Exception handlers complete
192-168-10-98 Chef Client failed. 0 resources updated in 03 seconds
192-168-10-98 [2015-10-12T16:34:36+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
192-168-10-98 [2015-10-12T16:34:36+00:00] ERROR: httpd_service_debian_sysvinit[customers] (awesome_customers::webserver line 7) had an error: NoMethodError: undefined method `each' for nil:NilClass
192-168-10-98 [2015-10-12T16:34:36+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by chenkirk** [comment]
I tried to do this on my vm running Mint. To make it work I had to specify a version for `httpd_service`.
````ruby
httpd_service 'customers' do
  mpm 'prefork'
  version '2.4'
  action [:create, :start]
end
````

**Comment by smessmer** [comment]
Same problem here (followed the same tutorial)

**Comment by tas50** [comment]
This should be resolved in the current release.  Feel free to open this back up if you're still seeing the problem
