### ISSUE TITLE
httpd_service_rhel_sysvinit.rb wrong number of arguments (0 for 1)

### ISSUE THREAD

**Issue by bcg62** [chef-cookbooks/httpd#52]
Seeing this with the recent update to the cookbook.

centos6.6
Chef: 12.5.1

```
================================================================================
           Error executing action `start` on resource 'httpd_service_rhel_sysvinit[test]'
           ================================================================================

           ArgumentError
           -------------
           wrong number of arguments (0 for 1)

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cookbooks/httpd/libraries/httpd_service_rhel_sysvinit.rb:13:in `block (2 levels) in <class:HttpdServiceRhelSysvinit>'
           /tmp/kitchen/cookbooks/httpd/libraries/httpd_service_rhel_sysvinit.rb:12:in `block in <class:HttpdServiceRhelSysvinit>'
```

**Comment by someara** [comment]
Hello! 

I locked this to a minimum version of compat_resource in the latest release.
https://github.com/chef-cookbooks/httpd/blob/3c1f7fe50ada912a2d2aff6860c265699e159aa7/metadata.rb

Are you still seeing this?

https://travis-ci.org/chef-cookbooks/httpd/builds/88028568

**Comment by bcg62** [comment]
looks like that fixed it. Thanks!
