### ISSUE TITLE
Changing the mpm module results in a fatal configuration error

### ISSUE THREAD

**Issue by mostwanted1976** [chef-cookbooks/httpd#57]
Changing the mpm module to be used for a `httpd_service` instance results in 2 enabled mpm module load files and this fatal error while running `sudo chef-client`:

```
      STDOUT: * Starting web server apache2
       * 
       * The apache2-example configtest failed.
      STDERR: Output of config test was:
      AH00534: apache2: Configuration error: More than one MPM loaded.
      Action 'configtest' failed.
```

Deleting one of the mpm module load files in `/etc/apache2-example/mods-enabled/` and executing `sudo chef-client` again solves the problem.

**I guess Chef should delete the obsolete mpm module load file if you change the mpm module in your Chef cookbook/recipe, right?**

More detailed output:

```
  * httpd_service_debian_sysvinit[example] action start
    * template[/etc/init.d/apache2-example] action create (up to date)
    * service[apache2-example] action start
      
      ================================================================================
      Error executing action `start` on resource 'service[apache2-example]'
      ================================================================================
      
      Mixlib::ShellOut::ShellCommandFailed
      ------------------------------------
      Expected process to exit with [0], but received '1'
      ---- Begin output of /etc/init.d/apache2-example start ----
      STDOUT: * Starting web server apache2
       * 
       * The apache2-example configtest failed.
      STDERR: Output of config test was:
      AH00534: apache2: Configuration error: More than one MPM loaded.
      Action 'configtest' failed.
      The Apache error log may have more information.
      ---- End output of /etc/init.d/apache2-example start ----
      Ran /etc/init.d/apache2-example start returned 1
      
      Cookbook Trace:
      ---------------
      /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:119:in `compile_and_converge_action'
      
      Resource Declaration:
      ---------------------
      # In /var/chef/cache/cookbooks/httpd/libraries/httpd_service_debian_sysvinit.rb
      
       19:       service "#{apache_name}" do
       20:         supports restart: true, reload: true, status: true
       21:         provider Chef::Provider::Service::Init::Debian
       22:         action [:start, :enable]
       23:       end
       24:     end
      
      Compiled Resource:
      ------------------
      # Declared in /var/chef/cache/cookbooks/httpd/libraries/httpd_service_debian_sysvinit.rb:19:in `block in <class:HttpdServiceDebianSysvinit>'
      
      service("apache2-example") do
        provider Chef::Provider::Service::Debian
        action [:start, :enable]
        supports {:restart=>true, :reload=>true, :status=>true}
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        service_name "apache2-example"
        pattern "apache2-example"
        declared_type :service
        cookbook_name "solid_webserver"
      end
      
    
    ================================================================================
    Error executing action `start` on resource 'httpd_service_debian_sysvinit[example]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    service[apache2-example] (/var/chef/cache/cookbooks/httpd/libraries/httpd_service_debian_sysvinit.rb line 19) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
    ---- Begin output of /etc/init.d/apache2-example start ----
    STDOUT: * Starting web server apache2
     * 
     * The apache2-example configtest failed.
    STDERR: Output of config test was:
    AH00534: apache2: Configuration error: More than one MPM loaded.
    Action 'configtest' failed.
    The Apache error log may have more information.
    ---- End output of /etc/init.d/apache2-example start ----
    Ran /etc/init.d/apache2-example start returned 1
    
    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:119:in `compile_and_converge_action'
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/solid_webserver/recipes/httpd.rb
    
      2: httpd_service 'example' do
      3:   mpm 'prefork'
      4:   action [:create, :start]
      5: end
      6: 
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/solid_webserver/recipes/httpd.rb:2:in `from_file'
    
    httpd_service_debian_sysvinit("example") do
      action [:create, :start]
      updated true
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :httpd_service
      cookbook_name "solid_webserver"
      recipe_name "httpd"
      mpm "prefork"
      version "2.4"
      package_name "apache2"
      instance "example"
      run_user "www-data"
      run_group "www-data"
      servername "localhost"
      maxclients "0"
      maxconnectionsperchild "0"
      maxrequestworkers "150"
      maxspareservers "10"
      minspareservers "5"
      startservers "5"
      modules ["authz_core", "authz_host", "authn_core", "auth_basic", "access_compat", "authn_file", "authz_user", "alias", "dir", "autoindex", "env", "mime", "negotiation", "setenvif", "filter", "deflate", "status"]
      timeout "400"
      log_level "warn"
      keepalive true
      maxkeepaliverequests "100"
      keepalivetimeout "5"
      hostname_lookups "off"
      listen_addresses ["0.0.0.0"]
      listen_ports ["80"]
    end
```

**Comment by eric-tucker** [comment]
I'm seeing this too.  Indeed, changing the mpm module should clean up mods enabled symlinks, not just conf enabled symlinks.
