### ISSUE TITLE
Amazon Linux 2016.03 does not correctly determine package name for httpd_service

### ISSUE THREAD

**Issue by eric-tucker** [chef-cookbooks/httpd#88]
### Cookbook version
0.4.0

### Chef-client version
12.5.1

### Platform Details
Amazon Linux 2016.03

### Scenario:
Install httpd_service

### Steps to Reproduce:
Single recipe with one resource:

```
httpd_service "default" do
  action [:create, :start]
end
```

### Expected Result:
Installs httpd 2.4

### Actual Result:
Stack trace:

```
  * httpd_service_rhel_sysvinit[default] action create[2016-07-06T11:46:02+00:00] WARN: Default value nil is invalid for property version of resource . Possible fixes: 1. Remove 'default: nil' if nil means 'undefined'. 2. Set a valid default value if there is a reasonable one. 3. Allow nil as a valid value of your property (for example, 'property :version, [ String, nil ], default: nil'). Error: Property version must be one of: String!  You passed nil. at /etc/chef/local-mode-cache/cache/cookbooks/httpd/libraries/helpers.rb:101:in `default_package_name'
[2016-07-06T11:46:02+00:00] WARN: Default value nil is invalid for property package_name of resource . Possible fixes: 1. Remove 'default: nil' if nil means 'undefined'. 2. Set a valid default value if there is a reasonable one. 3. Allow nil as a valid value of your property (for example, 'property :package_name, [ String, nil ], default: nil'). Error: Property package_name must be one of: String!  You passed nil. at /etc/chef/local-mode-cache/cache/cookbooks/httpd/libraries/httpd_service_rhel.rb:12:in `block in <class:HttpdServiceRhel>'

    
    ================================================================================
    Error executing action `create` on resource 'httpd_service_rhel_sysvinit[default]'
    ================================================================================
    
    ArgumentError
    -------------
    You must supply a name when declaring a package resource
    
    Cookbook Trace:
    ---------------
    /etc/chef/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/resource_builder.rb:60:in `build'
    /etc/chef/local-mode-cache/cache/cookbooks/httpd/libraries/httpd_service_rhel.rb:12:in `block in <class:HttpdServiceRhel>'
    /etc/chef/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:124:in `instance_eval'
    /etc/chef/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:124:in `compile_and_converge_action'
    /etc/chef/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
    
    Resource Declaration:
    ---------------------
    # In /etc/chef/local-mode-cache/cache/cookbooks/my-cookbook/recipes/default.rb
    
      1: httpd_service 'default' do
      2:   action [:create, :start]
      3: end
    
    Compiled Resource:
    ------------------
    # Declared in /etc/chef/local-mode-cache/cache/cookbooks/my-cookbook/recipes/default.rb:1:in `from_file'
    
    httpd_service_rhel_sysvinit("default") do
      action [:create, :start]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :httpd_service
      cookbook_name "my-cookbook"
      recipe_name "default"
    end
    

Running handlers:
[2016-07-06T11:46:02+00:00] ERROR: Running exception handlers
Running handlers complete
[2016-07-06T11:46:02+00:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 02 seconds
[2016-07-06T11:46:02+00:00] FATAL: Stacktrace dumped to /etc/chef/local-mode-cache/cache/chef-stacktrace.out
[2016-07-06T11:46:02+00:00] ERROR: httpd_service_rhel_sysvinit[default] (my-cookbook::default line 1) had an error: ArgumentError: You must supply a name when declaring a package resource
[2016-07-06T11:46:03+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by eric-tucker** [comment]
Please ignore.  I had not properly deployed the community cookbook via Berkshelf.  I'm a dohead!
